version: '3'

services:
  db:
    image: postgres
    environment:
        POSTGRES_DB: django
        POSTGERS_USER: django_user
        POSTGRES_PASSWORD: django_password
    volumes:
        - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
    db_data: